version = 0.1

[default.deploy.parameters]
stack_name = "hello-app"
resolve_s3 = true
s3_prefix = "hello-app"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-west-1"
